### ISSUE TITLE
iptables-persistentが無い環境があるっぽい

### ISSUE THREAD

**Issue by yupix** [joinmisskey/bash-install#2]
[こちら](https://ar.akarinext.org/notes/8qgmbz8th9)の方は`iptables-persistent`が入っておらず、grepの部分でこけたみたいなので、自動インストールに追加しといた方がいいと思います。

**Comment by tamaina** [comment]
https://github.com/joinmisskey/bash-install/commit/2c16388c04d263c65d27dc0268c75bf09d7e55de にて修正しました。Issueありがとうございます。
