### ISSUE TITLE
Redisインストール時に発生するバグ

### ISSUE THREAD

**Issue by d1hydr0gen** [joinmisskey/bash-install#24]
OS: Ubuntu 23.10 (x64)
RAM: 1GB + Swap 2GB
CPU: VPSのため不明 (1コア) ※選択したCPUは「Intel Regular Performance」と書いてあったもの
利用しているVPSプロバイダ: Vultr ※日本のTokyoローケーションを選択

シェスルクリプトから渡された選択肢 ※念のため
1. systemdを選択
2. リポジトリ関連は変更なし
3. ドメインは取得したものを入力
4. Nginxはセットアップしないを選んだ。
5. ポートは3000を選んだ
6. postgresはインストールするを選んだ。※DB設定は初期値を利用。パスワードは misskeyを利用(本番で試す前の検証のため)。
7. redisもインストールするを選んだ。

出るエラー
```
Process: prepare redis;
deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb mantic main
Process: apt install #2;
E: Failed to fetch https://packages.redis.io/deb/dists/mantic/InRelease  403  Forbidden [IP: 2600:9000:2247:9000:13:e54d:6980:93a1 443]
E: The repository 'https://packages.redis.io/deb mantic InRelease' is not signed.
```

対処方法をお教えいただけませんでしょうか？

**Comment by Srgr0** [comment]
403で弾かれている部分を確認してみたところ、redis側のサーバーで Ubuntu 23.10 Mantic Minotaur用のファイルが用意されていない可能性が高そうです。
特段理由のない限り、サーバー構築の際にはLTSバージョン(現時点で20.04 Focal / 22.04 Jammy)をご使用ください。

**Comment by d1hydr0gen** [comment]
ありがとうございます。
22.04を利用してみます!
