### ISSUE TITLE
Misskeyが起動しない

### ISSUE THREAD

**Issue by d1hydr0gen** [joinmisskey/bash-install#25]
環境(自宅鯖):
CPU: Intel Pentium inside (結構古いもの)
RAM 3GB + Swap 3GB、計6GBの環境

インストールしておいたもの:
Cloudflared (CF Tunnel) 
Zerotier-VPN(別マシンからSSHするため)

症状:
Misskeyが起動しない。

インストール時の選択:
1. systemdを選択。
2. リポジトリ関連はデフォルトのまま。
3. ドメインは misskey.buzzを選択
4. nginxはyesを選択
5. ポート解放関連は Noを選択(CFTunnelを利用するため)
6. CertBotはNoを選択。(CFTunnelで勝手にSSL化されるため)
7. Cloudflareを使用を選択(メールとAPIキーを正しく入力)
8. 3000ポートを指定。CFTunnelでmisskey.buzzをhttp://localhost:3000に転送するように設定.
9. PostgreSQLをインストールするを選択。 全部デフォルト(パスワードは"misskey"を利用)
10. Redisもインストールするを選択。パスワードは上記同様を利用.

エラー
```
Check: If Misskey starts correctly;
        NG.
Process: create misskey daemon;
Created symlink /etc/systemd/system/multi-user.target.wants/misskey.buzz.service → /etc/systemd/system/misskey.buzz.service.
● misskey.buzz.service - Misskey daemon
     Loaded: loaded (/etc/systemd/system/misskey.buzz.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2023-12-25 14:31:38 UTC; 16ms ago
   Main PID: 10782 (npm)
      Tasks: 1 (limit: 4405)
     Memory: 128.0K
        CPU: 5ms
     CGroup: /system.slice/misskey.buzz.service
             └─10782 /usr/bin/env node /usr/bin/npm start

Dec 25 14:31:38 misskey systemd[1]: Started Misskey daemon.

Process: create .misskey.env;
ALL MISSKEY INSTALLATION PROCESSES ARE COMPLETE!
Jump to https://misskey.buzz/ and continue setting up your instance.
This script version is v3.2.1.
Please follow @joinmisskey@misskey.io to address bugs and updates.
misskey@misskey:~$ 
```

スペック不足でしょうか...?

**Comment by Srgr0** [comment]
インストールに失敗しているのか、インストールは完了しているが起動に失敗しているのか、ご提示いただいた情報では判断できかねます。
インストールログと起動時のログの全文、各ソフトウェアのバージョンなど詳細情報をいただければお手伝いできるかもしれません。

**Comment by d1hydr0gen** [comment]
インストールログにエラーは見当たらなかったので、起動失敗はスペック不足だとおもいます。
別マシンにインストールしたところ、問題なくできたので、スペックの問題として自己解決しました。申し訳ありません。

これは提案なのですが、
スペック(CPUなど)の最小要件の目安などを書いてみるのもいいかもしれません....
