### ISSUE TITLE
提案：リポジトリ名の変更

### ISSUE THREAD

**Issue by Srgr0** [joinmisskey/bash-install#26]
### 提案理由
現在のリポジトリ名ではMisskeyに関連するリポジトリであることが明確でなく、リポジトリをダウンロードしたりcloneしたりした場合に内容が把握しにくいため。

### 改名案
Misskeyのインストールに関連するリポジトリであることが明確な名称
例：misskey-install, misskey-installer, misskey-install-script

**Comment by tamaina** [comment]
joinmisskey/bash-installで一つのリポジトリ名だと思っていたし、いろんなところのリンクを書き換えなければならないので個人的には前向きになれないなぁ
