### ISSUE TITLE
Ubuntu 22.04でPostgreSQLのインストールで詰まる？

### ISSUE THREAD

**Issue by tamaina** [joinmisskey/bash-install#6]
Multipass上のUbuntu 22.04 LTSではPostgreSQLで以下のようなエラーが発生する

![2022-11-10 23-17-10 1](https://user-images.githubusercontent.com/7973572/201117202-4b629333-16a2-404d-a116-23906126b067.png)

apt.postgresql.org.shを使わない方が良さそう？

**Comment by joseph-bravo** [comment]
Ubuntu 22.04 LTS,

Running the following prior to using the script ensures that it works.

```
sudo apt install postgresql-common
sudo sh /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
```
