### ISSUE TITLE
Bashでインストールするとメール配信が上手く行かない

### ISSUE THREAD

**Issue by PYU224** [joinmisskey/bash-install#9]
初めまして。
Bashにてsystemdでインストールしました。
misskeyの起動は上手く行けたんですが、メール配信にてメール配信機能を有効にして配信テストでテストメールを送ろうとすると
`Unexpected token '<', "<!DOCTYPE "... is not valid JSON`
`undefined`
というエラーが出てメールが送れません。
原因と対処をお願いします。

**Comment by tamaina** [comment]
全て手作業など他の方法でインストールした場合はメール配信がうまく動作するということでしょうか？

**Comment by PYU224** [comment]
それは試していません。
どうにもならなくなったら試そうかと思いますが・・・

**Comment by PYU224** [comment]
追加情報
telnetでポート25と587でSMTPは通りました。

**Comment by PYU224** [comment]
恐らく原因はプロバイダ周りでSMTP-AUTHが使えないのが原因だとにらんでいますがどうでしょうか？
http://graphtec.co.jp/site_support/qa/instrument/f-ins00280.html
